#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

AppIcon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAABIdJ'
    b'REFUeJztmm1olWUYx3/X/ZyXedyZO8c5RZfEsIY2k0QKwRAqRIKypHCmEYUVWYyE/CSBRiEF'
    b'0ak+TUrKsKAsCgLpQ6ARZi/Ulik5cuRcUw9bW9vZdt6e5+rDc6Zn6llzEPeHPT84Hx7O/fK/'
    b'fs99X5wPR8Q4zGSM7QC2CQTYDmCbQIDtALYJBNgOYJtAgO0AtgkE2A5gm0CA7QC2CQTYDmCb'
    b'QIDtALYJBNgOYJtAgO0AtgkE2A5gm0CA7QC2CQTYDmCbQIDtALYJBNgOYJtAgO0AtpnxAmSS'
    b'75K7Owq7dq8Ivw5c2PNr4ZziLJTSFEURBRWoCXmsna80zzGEy5SKXH7IXjjF4FcvU/irHUH9'
    b'reXyOmZWiOpbajCxEDL7JqqW7cVE6krrXB0zm83S2NjI+fPn1wLfTFfAZCdgmSjPO7ASSCrO'
    b'wvIvRUFQFsdcti2BlckQEccgcvlTTnT+Uuq3vk98zTOoGED9dRAQwR1zGWofxB0swEgn2d92'
    b'4OYuXhpXjqrS1tZGOp3uBI5Nt3gACf4kNcOZrAfE9nTkP4HQvQhQuu/jPSAR9tjeBAa55h29'
    b'kk97c+w6XWB5tfDW8ij1oQJ9H24j3/ML5dMVBQUJGeIranGqHUz8VobrXyCVaiOVSnFXc5h3'
    b'W+M0PNb7sAuH/hcBuzsKbwvmOUp3tBxFaZ6jPHiDL2QqAu78dpSTIyAqNFcrn98eYXZ+gP6D'
    b'j+P2nymlKTVY9XcxUYea2xJI1PDFkQF2vHaanRtreHJdFGNAkd7alp6lwNB0BVS6AklBnkLM'
    b'VcWDb82R8eKnttFg0UP8I8SJDGz+Oc9wpJa5LfswdUsmvAoRv/NrziVz8h9wPTasTXLqg5t5'
    b'en0EMeMN1FtoYPv1lTyRawpwYBWYSMVZCgN5RdHS26qMquKpB2oQlL1N8EqT4adBuO/7An86'
    b'86h7ZD+hRStRVX/xss5fHC4y0pkBPKqSSYjFJxzb/o8aHp16uVczvSYoQu+oIVMcD1rZggIX'
    b'sy4X8hBzlC0NYbY2hIga+H0E1n2X5+OBOHNb9hFb8RCoXFKg4jeffDpH9uyYHzhRD5FZpS0F'
    b'A4unXUeliS4cQ3R0sokucOBscQqnQHmjy8VVYcQ13P9Djg0/5hjz/GM+5AqtJz02tUPvmheZ'
    b's+FVTFWC8ZMg4l+zse4M+XQWEEzdAohEUUxPYnPPs4BXYfMFQN11CwAyCilUS8fySjz6Ci4v'
    b'/eFysCdfkuBdGqvqP3vq8U53jv3nPBBFBdqHhPbhiY1DgCN/G+45XmBn8W76Wg4xq/kBkBB+'
    b'Bn/caOcwxf48GIOpb+ipbTl3hwcHJqkvXX946CDQUGnAZC0stKej0AbOE1d2umG3yGd9BQaK'
    b'YFC2LILWxjA3xhwMQlE9Tgy5vNlV5Mt02W++/2iY4wIdlNUJ2Bg6w+qu94h1fY24eX+QEWY3'
    b'1RCeF0VFumvWHN0EHK+w5KrE4cxRI5rqXx/fdU0BwS/BGU4gwHYA2wQCbAewTSDAdgDbBAJs'
    b'B7BNIMB2ANsEAmwHsE0gwHYA28x4Af8CUvyIgclczkEAAAAASUVORK5CYII=')

